"""empty message

Revision ID: 571db502c6a6
Revises: 049a038d1fc7
Create Date: 2023-05-01 16:08:43.551164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '571db502c6a6'
down_revision = '049a038d1fc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('directreply', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('comment_directreply', 'comments', ['directreply'], ['commentid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('comment_directreply', type_='foreignkey')
        batch_op.drop_column('directreply')

    # ### end Alembic commands ###
